# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 17:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 29, 17, 41, 13, 842577, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
