# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0002_notifications_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='tracking_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
