# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 17:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0003_friends_tracking_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='from_friend_name',
            field=models.CharField(default=datetime.datetime(2016, 3, 1, 17, 2, 34, 619112, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
