# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0004_notifications_from_friend_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='lookupField',
            field=models.CharField(default='default_field', max_length=255),
        ),
    ]
