# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0005_friends_lookupfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
