# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0008_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_creator_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
