# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0009_events_event_creator_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='lookup_field',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
