# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-13 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0010_events_lookup_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='event_lookup_field',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
