# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-14 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0013_eventdetails_lookup_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdetails',
            name='lookup_field',
        ),
    ]
