# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-14 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0014_remove_eventdetails_lookup_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='lookup_field',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
